[package]
name = "tuat-feed-api"
version = "0.1.0"
authors = ["Shogo Takata <pineapplehunter.daniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuat-feed-parser={path="tuat-feed-parser"}
#serde = {version="1.0.104",features=["derive"]}
tide = "0.6.0"
async-std = {version = "1.5.0", features = ["attributes"]}
tokio = {version = "0.2.11", features = ["rt-core"], default-features = false}