[package]
name = "tuat-feed-api"
version = "0.1.0"
authors = ["Shogo Takata <pineapplehunter.daniel@gmail.com>"]
edition = "2018"
include = ["src/main.rs", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["tuat-feed-parser"]

[features]
default = ["cache"]
cache = []

[dependencies]
tuat-feed-parser = { path = "tuat-feed-parser" }
tokio = { version = "0.2", features = ["macros"] }
anyhow = "1.0"
warp = { version = "0.2", default-features = false }
env_logger = "0.7"
log = "0.4"
argh = "0.1.3"
