[package]
name = "tuat-feed-api"
version = "0.1.0"
authors = ["Shogo Takata <pineapplehunter.daniel@gmail.com>"]
edition = "2018"
include = ["src/main.rs", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["tuat-feed-parser"]

[features]
default = ["cache"]
cache = []

[dependencies]
tuat-feed-parser = { path = "tuat-feed-parser" }
tokio = { version = "1.0.1", features = ["full"] }
anyhow = "1.0.35"
warp = { version = "0.2.5", git = "https://github.com/seanmonstar/warp.git", default-features = false }
env_logger = "0.8.2"
log = "0.4.11"
argh = "0.1.4"
