name: Check and test

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  check_and_test:
    name: Check and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      # for local use
      - name: install gcc
        run: "which gcc && which pkg-config && pkg-config --libs --cflags openssl || bash -c 'apt update && apt install -y gcc pkg-config libssl-dev'"

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          override: true
          components: rustfmt, clippy

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{matrix.rust}}
          command: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{matrix.rust}}
          command: clippy
          args: --all --all-targets

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{matrix.rust}}
          command: test
          args: --all

      - name: clean cache
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo cache
