[package]
name = "tuat-feed-parser"
version = "0.1.0"
authors = ["Shogo Takata <pineapplehunter.daniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
scraper = "0.12"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.10", default-features = false }
futures = { version = "0.3", default-features = false }
thiserror = "1.0"
log = "0.4"

[dev-dependencies]
tokio = { version = "0.3", features = ["macros"] }
