[package]
name = "tuat-feed-parser"
version = "0.1.0"
authors = ["Shogo Takata <pineapplehunter.daniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.11.0"
serde = {version="1.0.104", features=["derive"]}
reqwest = "0.10.1"
futures = "0.3.4"
thiserror = "1.0.18"
